Update ghau5940uri.yml

diff --git a/.github/workflows/ghau5940uri.yml b/.github/workflows/ghau5940uri.yml
--- a/.github/workflows/ghau5940uri.yml
+++ b/.github/workflows/ghau5940uri.yml
@@ -23,22 +23,26 @@ jobs:
     - name: Scan the Target
       run: |
         target_url="${{ inputs.target-URL }}"
-        target-req="${{ inputs.target-Request }}"
+        target_req="${{ inputs.target-Request }}"
         sudo apt update
         sudo apt install git python3-pip -y
         git clone https://github.com/r0oth3x49/ghauri.git
         cd ghauri
         python3 -m pip install --upgrade -r requirements.txt
         sudo python3 setup.py install
-        echo "Ghauri Help Menu "
+        echo "Ghauri Help Menu"
         ghauri --help
-        if [[ -z "$target_url" ]]; then
-          echo "No URL given, scanning request"
-          ghauri -r "$target-req" -H "X-HackerOne-Research: ss82" --delay 0.166
-        else 
+        if [[ -n "$target_url" ]]; then
           echo "Scanning URL"
           ghauri -u "$target_url" -H "X-HackerOne-Research: ss82" --delay 0.166
-        fi  
+        elif [[ -n "$target_req" ]]; then
+          echo "No URL given, scanning request"
+          ghauri -r "$target_req" -H "X-HackerOne-Research: ss82" --delay 0.166
+        else
+          echo "Error: Both URL and request inputs are empty. Please provide at least one."
+        exit 1
+        fi
+
 
 
 
